### ISSUE TITLE
TODO Discussion

### ISSUE THREAD

**Issue by 3y3** [node-inspector/v8-debug#1]
- [x] Fix Linux building
- [x] Write tests for binary
- [x] Write tests for javascript
- [x] Extend API for node-inspector Profiler API
- [x] Extend API for node-inspector Console API
- [x] Add cleanup after debugger ```disconnect``` message
- [x] Add prebuild binaries
